export const metadata = function () {
    return {
        creatable: true,
        defaultCount: 10,
        defaultOrder: [],
        deletable: true,
        editable: true,
        pagination: true,
        fields: [
            {
                alias: "",
                parent: "",
                displayName: "ID",
                editable: false,
                generated: true,
                localizable: false,
                name: "id",
                nullable: false,
                orderable: false,
                readable: true,
                searchable: false,
                type: "id",
                unique: true,
                versionable: false,
                versioned: false,
                visible: false
            },
            {
                alias: "",
                parent: "",
                displayName: "Issue Date",
                editable: true,
                generated: false,
                localizable: false,
                name: "issue_date",
                nullable: true,
                orderable: true,
                readable: true,
                searchable: true,
                type: "datetime",
                unique: false,
                versionable: false,
                versioned: false,
                visible: true
            },
            {
                alias: "",
                parent: "",
                displayName: "Payment Date",
                editable: true,
                generated: false,
                localizable: false,
                name: "payment_date",
                nullable: true,
                orderable: true,
                readable: true,
                searchable: true,
                type: "datetime",
                unique: false,
                versionable: false,
                versioned: false,
                visible: true
            },
            {
                alias: "",
                parent: "",
                displayName: "Sub Total",
                editable: true,
                generated: false,
                localizable: false,
                name: "sub_total",
                nullable: true,
                orderable: true,
                readable: true,
                searchable: true,
                type: "number",
                unique: false,
                versionable: false,
                versioned: false,
                visible: true
            },
            {
                alias: "",
                parent: "",
                displayName: "Discount",
                editable: true,
                generated: false,
                localizable: false,
                name: "discount",
                nullable: true,
                orderable: true,
                readable: true,
                searchable: true,
                type: "number",
                unique: false,
                versionable: false,
                versioned: false,
                visible: true
            },
            {
                alias: "",
                parent: "",
                displayName: "Total",
                editable: true,
                generated: false,
                localizable: false,
                name: "total",
                nullable: true,
                orderable: true,
                readable: true,
                searchable: true,
                type: "number",
                unique: false,
                versionable: false,
                versioned: false,
                visible: true
            },
            {
                alias: "",
                parent: "",
                displayName: "Subscription Id",
                editable: true,
                generated: false,
                localizable: false,
                name: "subscription_details_id",
                nullable: false,
                orderable: true,
                readable: true,
                searchable: true,
                type: "reference",
                reference: {
                    kind: "single",
                    to: "subscription",
                    api: "list"
                },
                unique: false,
                versionable: false,
                versioned: false,
                visible: true
            },
            {
                alias: "",
                parent: "",
                displayName: "Stellar Id",
                editable: true,
                generated: false,
                localizable: false,
                name: "stellar_id",
                nullable: true,
                orderable: true,
                readable: true,
                searchable: true,
                type: "string",
                unique: false,
                versionable: false,
                versioned: false,
                visible: true
            },
            {
                alias: "",
                parent: "",
                displayName: "Stripe Payment Id",
                editable: true,
                generated: false,
                localizable: false,
                name: "stripe_payment_id",
                nullable: true,
                orderable: true,
                readable: true,
                searchable: true,
                type: "email",
                unique: true,
                versionable: false,
                versioned: false,
                visible: true
            }
        ]
    };
}