openapi: 3.0.0
info:
  title: 'Stellar Account'
  description: 'Stellar Account 1.0'
  termsOfService: https://www.interactivelife.com/terms/
  contact:
    email: support@interactivelife.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Interactivelife.com
  url: https://www.interactivelife.com
servers:
- url: http://localhost:8091/v3
  description: Development server
- url: https://api.staging.ili.ms/v3
  description: Staging server  
- url: https://api.stellar.online/v3
  description: Production server   